[package]
authors = ["The Knurling-rs developers"]
categories = ["command-line-utilities", "embedded", "no-std"]
description = "Runs embedded programs just like native ones"
edition = "2021"
keywords = ["knurling", "cargo-runner"]
license = "MIT OR Apache-2.0"
name = "probe-run"
readme = "README.md"
repository = "https://github.com/knurling-rs/probe-run"
version = "0.3.0"

[dependencies]
addr2line = { version = "0.15", default-features = false, features = [
    "fallible-iterator",
    "std-object",
] }
anyhow = "1"
colored = "2"
defmt-decoder = { version = "=0.3.0", features = ["unstable"] }
either = "1.6"
gimli = { version = "0.24", default-features = false }
git-version = "0.3"
log = "0.4"
object = { version = "0.24", default-features = false }
probe-rs = "0.11"
probe-rs-rtt = "0.11"
signal-hook = "0.3"
structopt = "0.3"

[dev-dependencies]
dirs = "4"
insta = "1.8"
os_pipe = "0.9"
pretty_assertions = "1"
rstest = "0.11"
nix = "0.23"
serial_test = "0.5"

[patch.crates-io.probe-rs]
git = "https://github.com/newAM/probe-rs.git"
rev = "862c584520519b57336ae159d8704a76fcd76d7d"
